### ISSUE TITLE
Error when expanding content (input elements) dynamically

### ISSUE THREAD

**Issue by mbornath** [pablo-abc/felte#26] opened 2021-06-09 11:29 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@felte/reporter-svelte@0.2.0` for the project I'm working on.

We are rendering a custom tree view inside a form. The tree nodes are expandable and contain input fields (checkboxes) with custom logic. When expanding the children of a node (with the corresponding checkboxes) the following error occured:

`Uncaught Error: Function called outside component initialization`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@felte/reporter-svelte/src/reporter.js b/node_modules/@felte/reporter-svelte/src/reporter.js
index 8c7aa8f..82b2aa7 100644
--- a/node_modules/@felte/reporter-svelte/src/reporter.js
+++ b/node_modules/@felte/reporter-svelte/src/reporter.js
@@ -7,7 +7,6 @@ import { getPath, _get } from '@felte/common';
  * @param {any} currentForm
  */
 export function svelteReporter(currentForm) {
-  if (!hasContext(formKey)) setContext(formKey, currentForm.errors);
   if (!currentForm.form) return;
   const unsubscribe = currentForm.errors.subscribe(($errors) => {
     for (const control of currentForm.controls) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by pablo-abc** [comment] 2021-06-09 14:46
I'm curious as to how you're using the reporter in this case, since removing this line completely removes the main feature of this package (using the `ValidationMessage` component) since they need to access that context.

**Comment by pablo-abc** [comment] 2021-06-15 16:51
I'm closing this for now since I can't reproduce this error and the proposed solution is not doable. Feel free to reopen this if you feel there's an actual bug to fix here.

For context, the error message shared:

`Uncaught Error: Function called outside component initialization`

Happens when you call `setContext` or `getContext` outside of a Svelte component or after the component initialises. This is why `createForm` should be used at the top level of the component.

**Closed by pablo-abc** 2021-06-15 16:51 UTC
