### ISSUE TITLE
@felte/validator-zod: Is dependency "zod" has wrong version?

### ISSUE THREAD

**Issue by ZirionNeft** [pablo-abc/felte#44] opened 2021-08-01 15:30 UTC
When I try to use Zod as form validator, I get errors. During in my research, I was concluded that possibly issue in wrong version of zod dependency after rollup.
Or object is null/undefined, and in condition a moment before need to check that "error" has own property "issues" otherwise should throw an error.

[Code line referenece in package](https://github.com/pablo-abc/felte/blob/a64f12a174ce74367dc77a6d57a7162a3992bd1b/packages/validator-zod/src/index.ts#L19)

Errors in console:
![image](https://user-images.githubusercontent.com/23456328/127776269-62ebf96e-6dc0-4d94-94fe-b8c59593a2cf.png)

**Comment by pablo-abc** [comment] 2021-08-01 19:26
Later versions of `validator-zod` depend on you having `zod@^3.0.0` since that's the latest stable version now. If you're using v1 that might be the issue.

**Comment by pablo-abc** [comment] 2021-08-01 20:01
On a second look, yes. Zod v3 introduced `issues` instead of `errors`. You should be using Zod v3 for the later versions of `@felte/validator-zod`

**Comment by benbender** [comment] 2021-08-01 20:37
@ZirionNeft to better understand your problem, a trace in development-mode, the output of `npm why zod` and a basic reproduction-case would be very helpful!

**Comment by ZirionNeft** [comment] 2021-08-02 09:46
> Later versions of `validator-zod` depend on you having `zod@^3.0.0` since that's the latest stable version now. If you're using v1 that might be the issue.

I have use one of latest version (3.5.1) and even trying to use as resolution. Nothing changes

> @ZirionNeft to better understand your problem, a trace in development-mode, the output of `npm why zod` and a basic reproduction-case would be very helpful!

So sorry, but I have already found other solution, and currently not using Zod and rest of it. 
If I will find time in weekends, I could try to reproduce my error

**Comment by pablo-abc** [comment] 2021-08-02 11:00
@ZirionNeft I actually just found something that might be causing this. `validator-zod` was actually bundling a version of `zod` with it (although it should have worked since it was `^3.2.0`). I've removed that and tested it locally and it works perfectly for me so I'll be closing this issue for now 😅. If you _do_ find this is still happening, please feel free to reopen this issue.

**Closed by pablo-abc** 2021-08-02 11:00 UTC
