### ISSUE TITLE
Felte does not update even though FormData was updated.

### ISSUE THREAD

**Issue by Leftium** [pablo-abc/felte#207] opened 2022-12-28 22:31 UTC
### Describe the bug

There are instances when Felte does not get updated even though FormData has changed.

For example, a minimal reproduction:
- Live demo: https://kit-bugs-git-felte-select-validation-bug-leftium.vercel.app/
- Source code: https://github.com/Leftium/kit-bugs/blob/felte-select-validation-bug/src/routes/%2Bpage.svelte

---

- In this demo, a `<select multiple>` has an `<option>` programmatically selected when the page loads.
- The FormData (`dataFromForm`) updates to reflect this change.
- But Felte's `data` store remains unchanged.
- Furthermore, trying to submit the form results in a validation error.
- Felte's `data` store is not updated until an `<option>` is manually selected.

### Which package/s are you using?

felte (Svelte), @felte/validator-zod

### Environment

- OS: Windows 11
- Browser: Chrome Version 108.0.5359.125 (Official Build) (64-bit)
- Version: felte@1.2.6, @felte/validator-zod@1.0.12

### To reproduce

1. Go to https://kit-bugs-git-felte-select-validation-bug-leftium.vercel.app/
2. Try to submit the form
3. See validation error, even though select value contains an element according to FormData (`dataFromForm`)
4. See Felte data has not updated to reflect actual status of select input.

### Small reproduction example

https://kit-bugs-git-felte-select-validation-bug-leftium.vercel.app/

### Additional context

**Workaround:** due to this issue, I have resorted to manually syncing Felte to the actual FormData values by converting FormData to a value in the same shape as Felte's value, then resetting via Felte's `setInitialValues()` and `reset()`

**Comment by pablo-abc** [comment] 2023-08-29 22:19
This is sort of an intended behaviour. Felte can't react to programmatic changes of your inputs since it relies on `events` being thrown when it changes. Programmatically changing attributes/properties does _not_ trigger any event.

In these situations I'd recommend using Felte itself as the source of truth. And if you need to programmatically change using, to use the [`setFields` helper](https://felte.dev/docs/svelte/helper-functions#setters) (or calling `setData` when you're doing your change if you want to sync them manually).

Closing this since it's technically not a bug 😅

**Closed by pablo-abc** 2023-08-29 22:19 UTC
Labels: bug
